# Generated by Django 2.0.2 on 2018-02-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
