# Generated by Django 2.0.1 on 2018-02-27 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fact_flow', '0004_auto_20180225_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
