# Generated by Django 2.0.2 on 2018-03-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_flow', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='end_index',
        ),
    ]
